/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth.verify-otp'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as AuthenticatedTraceabilityRouteImport } from './routes/_authenticated/traceability'
import { Route as AuthenticatedTeamManagementRouteImport } from './routes/_authenticated/team-management'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedSilosRouteImport } from './routes/_authenticated/silos'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServerMonitoringRouteImport } from './routes/_authenticated/server-monitoring'
import { Route as AuthenticatedSensorsRouteImport } from './routes/_authenticated/sensors'
import { Route as AuthenticatedSecurityCenterRouteImport } from './routes/_authenticated/security-center'
import { Route as AuthenticatedRevenueRouteImport } from './routes/_authenticated/revenue'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNotAllowedRouteImport } from './routes/_authenticated/not-allowed'
import { Route as AuthenticatedMlModelsRouteImport } from './routes/_authenticated/ml-models'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedInsuranceRouteImport } from './routes/_authenticated/insurance'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated/incidents'
import { Route as AuthenticatedGrainBatchesRouteImport } from './routes/_authenticated/grain-batches'
import { Route as AuthenticatedGrainAlertsRouteImport } from './routes/_authenticated/grain-alerts'
import { Route as AuthenticatedEnvironmentalRouteImport } from './routes/_authenticated/environmental'
import { Route as AuthenticatedDataVisualizationRouteImport } from './routes/_authenticated/data-visualization'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBuyersRouteImport } from './routes/_authenticated/buyers'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiPredictionsRouteImport } from './routes/_authenticated/ai-predictions'
import { Route as AuthenticatedActuatorsRouteImport } from './routes/_authenticated/actuators'
import { Route as AuthenticatedActivityLogsRouteImport } from './routes/_authenticated/activity-logs'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform.index'
import { Route as ApiFirebaseLiveSensorsRouteImport } from './routes/api/firebase/live-sensors'
import { Route as AuthenticatedPlatformUsersRouteImport } from './routes/_authenticated/platform.users'
import { Route as AuthenticatedPlatformTenantsRouteImport } from './routes/_authenticated/platform.tenants'
import { Route as AuthenticatedPlatformRevenueRouteImport } from './routes/_authenticated/platform.revenue'
import { Route as AuthenticatedPlatformOrdersRouteImport } from './routes/_authenticated/platform.orders'
import { Route as AuthenticatedPlatformLogsRouteImport } from './routes/_authenticated/platform.logs'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicHooksSensorOfflineDetectorRouteImport } from './routes/api/public/hooks/sensor-offline-detector'
import { Route as ApiPublicHooksExpiryRemindersRouteImport } from './routes/api/public/hooks/expiry-reminders'
import { Route as ApiPublicHooksAlertsEscalationRouteImport } from './routes/api/public/hooks/alerts-escalation'
import { Route as ApiPublicCronSyncFirebaseRouteImport } from './routes/api/public/cron/sync-firebase'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTraceabilityRoute =
  AuthenticatedTraceabilityRouteImport.update({
    id: '/traceability',
    path: '/traceability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamManagementRoute =
  AuthenticatedTeamManagementRouteImport.update({
    id: '/team-management',
    path: '/team-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSilosRoute = AuthenticatedSilosRouteImport.update({
  id: '/silos',
  path: '/silos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServerMonitoringRoute =
  AuthenticatedServerMonitoringRouteImport.update({
    id: '/server-monitoring',
    path: '/server-monitoring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSensorsRoute = AuthenticatedSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityCenterRoute =
  AuthenticatedSecurityCenterRouteImport.update({
    id: '/security-center',
    path: '/security-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRevenueRoute = AuthenticatedRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotAllowedRoute = AuthenticatedNotAllowedRouteImport.update({
  id: '/not-allowed',
  path: '/not-allowed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMlModelsRoute = AuthenticatedMlModelsRouteImport.update({
  id: '/ml-models',
  path: '/ml-models',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsuranceRoute = AuthenticatedInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrainBatchesRoute =
  AuthenticatedGrainBatchesRouteImport.update({
    id: '/grain-batches',
    path: '/grain-batches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGrainAlertsRoute =
  AuthenticatedGrainAlertsRouteImport.update({
    id: '/grain-alerts',
    path: '/grain-alerts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnvironmentalRoute =
  AuthenticatedEnvironmentalRouteImport.update({
    id: '/environmental',
    path: '/environmental',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDataVisualizationRoute =
  AuthenticatedDataVisualizationRouteImport.update({
    id: '/data-visualization',
    path: '/data-visualization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyersRoute = AuthenticatedBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiPredictionsRoute =
  AuthenticatedAiPredictionsRouteImport.update({
    id: '/ai-predictions',
    path: '/ai-predictions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActuatorsRoute = AuthenticatedActuatorsRouteImport.update({
  id: '/actuators',
  path: '/actuators',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityLogsRoute =
  AuthenticatedActivityLogsRouteImport.update({
    id: '/activity-logs',
    path: '/activity-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const ApiFirebaseLiveSensorsRoute = ApiFirebaseLiveSensorsRouteImport.update({
  id: '/api/firebase/live-sensors',
  path: '/api/firebase/live-sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlatformUsersRoute =
  AuthenticatedPlatformUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformTenantsRoute =
  AuthenticatedPlatformTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformRevenueRoute =
  AuthenticatedPlatformRevenueRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformOrdersRoute =
  AuthenticatedPlatformOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformLogsRoute =
  AuthenticatedPlatformLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSensorOfflineDetectorRoute =
  ApiPublicHooksSensorOfflineDetectorRouteImport.update({
    id: '/api/public/hooks/sensor-offline-detector',
    path: '/api/public/hooks/sensor-offline-detector',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExpiryRemindersRoute =
  ApiPublicHooksExpiryRemindersRouteImport.update({
    id: '/api/public/hooks/expiry-reminders',
    path: '/api/public/hooks/expiry-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAlertsEscalationRoute =
  ApiPublicHooksAlertsEscalationRouteImport.update({
    id: '/api/public/hooks/alerts-escalation',
    path: '/api/public/hooks/alerts-escalation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSyncFirebaseRoute =
  ApiPublicCronSyncFirebaseRouteImport.update({
    id: '/api/public/cron/sync-firebase',
    path: '/api/public/cron/sync-firebase',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/actuators': typeof AuthenticatedActuatorsRoute
  '/ai-predictions': typeof AuthenticatedAiPredictionsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/buyers': typeof AuthenticatedBuyersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-visualization': typeof AuthenticatedDataVisualizationRoute
  '/environmental': typeof AuthenticatedEnvironmentalRoute
  '/grain-alerts': typeof AuthenticatedGrainAlertsRoute
  '/grain-batches': typeof AuthenticatedGrainBatchesRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/ml-models': typeof AuthenticatedMlModelsRoute
  '/not-allowed': typeof AuthenticatedNotAllowedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/security-center': typeof AuthenticatedSecurityCenterRoute
  '/sensors': typeof AuthenticatedSensorsRoute
  '/server-monitoring': typeof AuthenticatedServerMonitoringRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/silos': typeof AuthenticatedSilosRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/team-management': typeof AuthenticatedTeamManagementRoute
  '/traceability': typeof AuthenticatedTraceabilityRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/platform/logs': typeof AuthenticatedPlatformLogsRoute
  '/platform/orders': typeof AuthenticatedPlatformOrdersRoute
  '/platform/revenue': typeof AuthenticatedPlatformRevenueRoute
  '/platform/tenants': typeof AuthenticatedPlatformTenantsRoute
  '/platform/users': typeof AuthenticatedPlatformUsersRoute
  '/api/firebase/live-sensors': typeof ApiFirebaseLiveSensorsRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
  '/api/public/cron/sync-firebase': typeof ApiPublicCronSyncFirebaseRoute
  '/api/public/hooks/alerts-escalation': typeof ApiPublicHooksAlertsEscalationRoute
  '/api/public/hooks/expiry-reminders': typeof ApiPublicHooksExpiryRemindersRoute
  '/api/public/hooks/sensor-offline-detector': typeof ApiPublicHooksSensorOfflineDetectorRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/actuators': typeof AuthenticatedActuatorsRoute
  '/ai-predictions': typeof AuthenticatedAiPredictionsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/buyers': typeof AuthenticatedBuyersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-visualization': typeof AuthenticatedDataVisualizationRoute
  '/environmental': typeof AuthenticatedEnvironmentalRoute
  '/grain-alerts': typeof AuthenticatedGrainAlertsRoute
  '/grain-batches': typeof AuthenticatedGrainBatchesRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/ml-models': typeof AuthenticatedMlModelsRoute
  '/not-allowed': typeof AuthenticatedNotAllowedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/security-center': typeof AuthenticatedSecurityCenterRoute
  '/sensors': typeof AuthenticatedSensorsRoute
  '/server-monitoring': typeof AuthenticatedServerMonitoringRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/silos': typeof AuthenticatedSilosRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/team-management': typeof AuthenticatedTeamManagementRoute
  '/traceability': typeof AuthenticatedTraceabilityRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/checkout': typeof CheckoutIndexRoute
  '/platform/logs': typeof AuthenticatedPlatformLogsRoute
  '/platform/orders': typeof AuthenticatedPlatformOrdersRoute
  '/platform/revenue': typeof AuthenticatedPlatformRevenueRoute
  '/platform/tenants': typeof AuthenticatedPlatformTenantsRoute
  '/platform/users': typeof AuthenticatedPlatformUsersRoute
  '/api/firebase/live-sensors': typeof ApiFirebaseLiveSensorsRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
  '/api/public/cron/sync-firebase': typeof ApiPublicCronSyncFirebaseRoute
  '/api/public/hooks/alerts-escalation': typeof ApiPublicHooksAlertsEscalationRoute
  '/api/public/hooks/expiry-reminders': typeof ApiPublicHooksExpiryRemindersRoute
  '/api/public/hooks/sensor-offline-detector': typeof ApiPublicHooksSensorOfflineDetectorRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/_authenticated/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/_authenticated/actuators': typeof AuthenticatedActuatorsRoute
  '/_authenticated/ai-predictions': typeof AuthenticatedAiPredictionsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/buyers': typeof AuthenticatedBuyersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/data-visualization': typeof AuthenticatedDataVisualizationRoute
  '/_authenticated/environmental': typeof AuthenticatedEnvironmentalRoute
  '/_authenticated/grain-alerts': typeof AuthenticatedGrainAlertsRoute
  '/_authenticated/grain-batches': typeof AuthenticatedGrainBatchesRoute
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRoute
  '/_authenticated/insurance': typeof AuthenticatedInsuranceRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/ml-models': typeof AuthenticatedMlModelsRoute
  '/_authenticated/not-allowed': typeof AuthenticatedNotAllowedRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/revenue': typeof AuthenticatedRevenueRoute
  '/_authenticated/security-center': typeof AuthenticatedSecurityCenterRoute
  '/_authenticated/sensors': typeof AuthenticatedSensorsRoute
  '/_authenticated/server-monitoring': typeof AuthenticatedServerMonitoringRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/silos': typeof AuthenticatedSilosRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/team-management': typeof AuthenticatedTeamManagementRoute
  '/_authenticated/traceability': typeof AuthenticatedTraceabilityRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/_authenticated/platform/logs': typeof AuthenticatedPlatformLogsRoute
  '/_authenticated/platform/orders': typeof AuthenticatedPlatformOrdersRoute
  '/_authenticated/platform/revenue': typeof AuthenticatedPlatformRevenueRoute
  '/_authenticated/platform/tenants': typeof AuthenticatedPlatformTenantsRoute
  '/_authenticated/platform/users': typeof AuthenticatedPlatformUsersRoute
  '/api/firebase/live-sensors': typeof ApiFirebaseLiveSensorsRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
  '/api/public/cron/sync-firebase': typeof ApiPublicCronSyncFirebaseRoute
  '/api/public/hooks/alerts-escalation': typeof ApiPublicHooksAlertsEscalationRoute
  '/api/public/hooks/expiry-reminders': typeof ApiPublicHooksExpiryRemindersRoute
  '/api/public/hooks/sensor-offline-detector': typeof ApiPublicHooksSensorOfflineDetectorRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/checkout'
    | '/contact'
    | '/docs'
    | '/help'
    | '/privacy'
    | '/sitemap.xml'
    | '/team'
    | '/terms'
    | '/activity-logs'
    | '/actuators'
    | '/ai-predictions'
    | '/analytics'
    | '/buyers'
    | '/dashboard'
    | '/data-visualization'
    | '/environmental'
    | '/grain-alerts'
    | '/grain-batches'
    | '/incidents'
    | '/insurance'
    | '/maintenance'
    | '/ml-models'
    | '/not-allowed'
    | '/notifications'
    | '/orders'
    | '/plans'
    | '/platform'
    | '/reports'
    | '/revenue'
    | '/security-center'
    | '/sensors'
    | '/server-monitoring'
    | '/settings'
    | '/silos'
    | '/subscription'
    | '/team-management'
    | '/traceability'
    | '/warehouses'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/checkout/success'
    | '/checkout/'
    | '/platform/logs'
    | '/platform/orders'
    | '/platform/revenue'
    | '/platform/tenants'
    | '/platform/users'
    | '/api/firebase/live-sensors'
    | '/platform/'
    | '/api/public/cron/sync-firebase'
    | '/api/public/hooks/alerts-escalation'
    | '/api/public/hooks/expiry-reminders'
    | '/api/public/hooks/sensor-offline-detector'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/docs'
    | '/help'
    | '/privacy'
    | '/sitemap.xml'
    | '/team'
    | '/terms'
    | '/activity-logs'
    | '/actuators'
    | '/ai-predictions'
    | '/analytics'
    | '/buyers'
    | '/dashboard'
    | '/data-visualization'
    | '/environmental'
    | '/grain-alerts'
    | '/grain-batches'
    | '/incidents'
    | '/insurance'
    | '/maintenance'
    | '/ml-models'
    | '/not-allowed'
    | '/notifications'
    | '/orders'
    | '/plans'
    | '/reports'
    | '/revenue'
    | '/security-center'
    | '/sensors'
    | '/server-monitoring'
    | '/settings'
    | '/silos'
    | '/subscription'
    | '/team-management'
    | '/traceability'
    | '/warehouses'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/checkout/success'
    | '/checkout'
    | '/platform/logs'
    | '/platform/orders'
    | '/platform/revenue'
    | '/platform/tenants'
    | '/platform/users'
    | '/api/firebase/live-sensors'
    | '/platform'
    | '/api/public/cron/sync-firebase'
    | '/api/public/hooks/alerts-escalation'
    | '/api/public/hooks/expiry-reminders'
    | '/api/public/hooks/sensor-offline-detector'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/checkout'
    | '/contact'
    | '/docs'
    | '/help'
    | '/privacy'
    | '/sitemap.xml'
    | '/team'
    | '/terms'
    | '/_authenticated/activity-logs'
    | '/_authenticated/actuators'
    | '/_authenticated/ai-predictions'
    | '/_authenticated/analytics'
    | '/_authenticated/buyers'
    | '/_authenticated/dashboard'
    | '/_authenticated/data-visualization'
    | '/_authenticated/environmental'
    | '/_authenticated/grain-alerts'
    | '/_authenticated/grain-batches'
    | '/_authenticated/incidents'
    | '/_authenticated/insurance'
    | '/_authenticated/maintenance'
    | '/_authenticated/ml-models'
    | '/_authenticated/not-allowed'
    | '/_authenticated/notifications'
    | '/_authenticated/orders'
    | '/_authenticated/plans'
    | '/_authenticated/platform'
    | '/_authenticated/reports'
    | '/_authenticated/revenue'
    | '/_authenticated/security-center'
    | '/_authenticated/sensors'
    | '/_authenticated/server-monitoring'
    | '/_authenticated/settings'
    | '/_authenticated/silos'
    | '/_authenticated/subscription'
    | '/_authenticated/team-management'
    | '/_authenticated/traceability'
    | '/_authenticated/warehouses'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/checkout/success'
    | '/checkout/'
    | '/_authenticated/platform/logs'
    | '/_authenticated/platform/orders'
    | '/_authenticated/platform/revenue'
    | '/_authenticated/platform/tenants'
    | '/_authenticated/platform/users'
    | '/api/firebase/live-sensors'
    | '/_authenticated/platform/'
    | '/api/public/cron/sync-firebase'
    | '/api/public/hooks/alerts-escalation'
    | '/api/public/hooks/expiry-reminders'
    | '/api/public/hooks/sensor-offline-detector'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  ApiFirebaseLiveSensorsRoute: typeof ApiFirebaseLiveSensorsRoute
  ApiPublicCronSyncFirebaseRoute: typeof ApiPublicCronSyncFirebaseRoute
  ApiPublicHooksAlertsEscalationRoute: typeof ApiPublicHooksAlertsEscalationRoute
  ApiPublicHooksExpiryRemindersRoute: typeof ApiPublicHooksExpiryRemindersRoute
  ApiPublicHooksSensorOfflineDetectorRoute: typeof ApiPublicHooksSensorOfflineDetectorRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/traceability': {
      id: '/_authenticated/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof AuthenticatedTraceabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-management': {
      id: '/_authenticated/team-management'
      path: '/team-management'
      fullPath: '/team-management'
      preLoaderRoute: typeof AuthenticatedTeamManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/silos': {
      id: '/_authenticated/silos'
      path: '/silos'
      fullPath: '/silos'
      preLoaderRoute: typeof AuthenticatedSilosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/server-monitoring': {
      id: '/_authenticated/server-monitoring'
      path: '/server-monitoring'
      fullPath: '/server-monitoring'
      preLoaderRoute: typeof AuthenticatedServerMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sensors': {
      id: '/_authenticated/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof AuthenticatedSensorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security-center': {
      id: '/_authenticated/security-center'
      path: '/security-center'
      fullPath: '/security-center'
      preLoaderRoute: typeof AuthenticatedSecurityCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revenue': {
      id: '/_authenticated/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AuthenticatedRevenueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/not-allowed': {
      id: '/_authenticated/not-allowed'
      path: '/not-allowed'
      fullPath: '/not-allowed'
      preLoaderRoute: typeof AuthenticatedNotAllowedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ml-models': {
      id: '/_authenticated/ml-models'
      path: '/ml-models'
      fullPath: '/ml-models'
      preLoaderRoute: typeof AuthenticatedMlModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurance': {
      id: '/_authenticated/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof AuthenticatedInsuranceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grain-batches': {
      id: '/_authenticated/grain-batches'
      path: '/grain-batches'
      fullPath: '/grain-batches'
      preLoaderRoute: typeof AuthenticatedGrainBatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grain-alerts': {
      id: '/_authenticated/grain-alerts'
      path: '/grain-alerts'
      fullPath: '/grain-alerts'
      preLoaderRoute: typeof AuthenticatedGrainAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/environmental': {
      id: '/_authenticated/environmental'
      path: '/environmental'
      fullPath: '/environmental'
      preLoaderRoute: typeof AuthenticatedEnvironmentalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-visualization': {
      id: '/_authenticated/data-visualization'
      path: '/data-visualization'
      fullPath: '/data-visualization'
      preLoaderRoute: typeof AuthenticatedDataVisualizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyers': {
      id: '/_authenticated/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof AuthenticatedBuyersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-predictions': {
      id: '/_authenticated/ai-predictions'
      path: '/ai-predictions'
      fullPath: '/ai-predictions'
      preLoaderRoute: typeof AuthenticatedAiPredictionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actuators': {
      id: '/_authenticated/actuators'
      path: '/actuators'
      fullPath: '/actuators'
      preLoaderRoute: typeof AuthenticatedActuatorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity-logs': {
      id: '/_authenticated/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof AuthenticatedActivityLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/api/firebase/live-sensors': {
      id: '/api/firebase/live-sensors'
      path: '/api/firebase/live-sensors'
      fullPath: '/api/firebase/live-sensors'
      preLoaderRoute: typeof ApiFirebaseLiveSensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/platform/users': {
      id: '/_authenticated/platform/users'
      path: '/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof AuthenticatedPlatformUsersRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/tenants': {
      id: '/_authenticated/platform/tenants'
      path: '/tenants'
      fullPath: '/platform/tenants'
      preLoaderRoute: typeof AuthenticatedPlatformTenantsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/revenue': {
      id: '/_authenticated/platform/revenue'
      path: '/revenue'
      fullPath: '/platform/revenue'
      preLoaderRoute: typeof AuthenticatedPlatformRevenueRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/orders': {
      id: '/_authenticated/platform/orders'
      path: '/orders'
      fullPath: '/platform/orders'
      preLoaderRoute: typeof AuthenticatedPlatformOrdersRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/logs': {
      id: '/_authenticated/platform/logs'
      path: '/logs'
      fullPath: '/platform/logs'
      preLoaderRoute: typeof AuthenticatedPlatformLogsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sensor-offline-detector': {
      id: '/api/public/hooks/sensor-offline-detector'
      path: '/api/public/hooks/sensor-offline-detector'
      fullPath: '/api/public/hooks/sensor-offline-detector'
      preLoaderRoute: typeof ApiPublicHooksSensorOfflineDetectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/expiry-reminders': {
      id: '/api/public/hooks/expiry-reminders'
      path: '/api/public/hooks/expiry-reminders'
      fullPath: '/api/public/hooks/expiry-reminders'
      preLoaderRoute: typeof ApiPublicHooksExpiryRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/alerts-escalation': {
      id: '/api/public/hooks/alerts-escalation'
      path: '/api/public/hooks/alerts-escalation'
      fullPath: '/api/public/hooks/alerts-escalation'
      preLoaderRoute: typeof ApiPublicHooksAlertsEscalationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync-firebase': {
      id: '/api/public/cron/sync-firebase'
      path: '/api/public/cron/sync-firebase'
      fullPath: '/api/public/cron/sync-firebase'
      preLoaderRoute: typeof ApiPublicCronSyncFirebaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPlatformRouteChildren {
  AuthenticatedPlatformLogsRoute: typeof AuthenticatedPlatformLogsRoute
  AuthenticatedPlatformOrdersRoute: typeof AuthenticatedPlatformOrdersRoute
  AuthenticatedPlatformRevenueRoute: typeof AuthenticatedPlatformRevenueRoute
  AuthenticatedPlatformTenantsRoute: typeof AuthenticatedPlatformTenantsRoute
  AuthenticatedPlatformUsersRoute: typeof AuthenticatedPlatformUsersRoute
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
}

const AuthenticatedPlatformRouteChildren: AuthenticatedPlatformRouteChildren = {
  AuthenticatedPlatformLogsRoute: AuthenticatedPlatformLogsRoute,
  AuthenticatedPlatformOrdersRoute: AuthenticatedPlatformOrdersRoute,
  AuthenticatedPlatformRevenueRoute: AuthenticatedPlatformRevenueRoute,
  AuthenticatedPlatformTenantsRoute: AuthenticatedPlatformTenantsRoute,
  AuthenticatedPlatformUsersRoute: AuthenticatedPlatformUsersRoute,
  AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
}

const AuthenticatedPlatformRouteWithChildren =
  AuthenticatedPlatformRoute._addFileChildren(
    AuthenticatedPlatformRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityLogsRoute: typeof AuthenticatedActivityLogsRoute
  AuthenticatedActuatorsRoute: typeof AuthenticatedActuatorsRoute
  AuthenticatedAiPredictionsRoute: typeof AuthenticatedAiPredictionsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBuyersRoute: typeof AuthenticatedBuyersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDataVisualizationRoute: typeof AuthenticatedDataVisualizationRoute
  AuthenticatedEnvironmentalRoute: typeof AuthenticatedEnvironmentalRoute
  AuthenticatedGrainAlertsRoute: typeof AuthenticatedGrainAlertsRoute
  AuthenticatedGrainBatchesRoute: typeof AuthenticatedGrainBatchesRoute
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRoute
  AuthenticatedInsuranceRoute: typeof AuthenticatedInsuranceRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMlModelsRoute: typeof AuthenticatedMlModelsRoute
  AuthenticatedNotAllowedRoute: typeof AuthenticatedNotAllowedRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRevenueRoute: typeof AuthenticatedRevenueRoute
  AuthenticatedSecurityCenterRoute: typeof AuthenticatedSecurityCenterRoute
  AuthenticatedSensorsRoute: typeof AuthenticatedSensorsRoute
  AuthenticatedServerMonitoringRoute: typeof AuthenticatedServerMonitoringRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSilosRoute: typeof AuthenticatedSilosRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedTeamManagementRoute: typeof AuthenticatedTeamManagementRoute
  AuthenticatedTraceabilityRoute: typeof AuthenticatedTraceabilityRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityLogsRoute: AuthenticatedActivityLogsRoute,
  AuthenticatedActuatorsRoute: AuthenticatedActuatorsRoute,
  AuthenticatedAiPredictionsRoute: AuthenticatedAiPredictionsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBuyersRoute: AuthenticatedBuyersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDataVisualizationRoute: AuthenticatedDataVisualizationRoute,
  AuthenticatedEnvironmentalRoute: AuthenticatedEnvironmentalRoute,
  AuthenticatedGrainAlertsRoute: AuthenticatedGrainAlertsRoute,
  AuthenticatedGrainBatchesRoute: AuthenticatedGrainBatchesRoute,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRoute,
  AuthenticatedInsuranceRoute: AuthenticatedInsuranceRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMlModelsRoute: AuthenticatedMlModelsRoute,
  AuthenticatedNotAllowedRoute: AuthenticatedNotAllowedRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRevenueRoute: AuthenticatedRevenueRoute,
  AuthenticatedSecurityCenterRoute: AuthenticatedSecurityCenterRoute,
  AuthenticatedSensorsRoute: AuthenticatedSensorsRoute,
  AuthenticatedServerMonitoringRoute: AuthenticatedServerMonitoringRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSilosRoute: AuthenticatedSilosRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedTeamManagementRoute: AuthenticatedTeamManagementRoute,
  AuthenticatedTraceabilityRoute: AuthenticatedTraceabilityRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  ApiFirebaseLiveSensorsRoute: ApiFirebaseLiveSensorsRoute,
  ApiPublicCronSyncFirebaseRoute: ApiPublicCronSyncFirebaseRoute,
  ApiPublicHooksAlertsEscalationRoute: ApiPublicHooksAlertsEscalationRoute,
  ApiPublicHooksExpiryRemindersRoute: ApiPublicHooksExpiryRemindersRoute,
  ApiPublicHooksSensorOfflineDetectorRoute:
    ApiPublicHooksSensorOfflineDetectorRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
