/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as AuthenticatedTraceabilityRouteImport } from './routes/_authenticated/traceability'
import { Route as AuthenticatedTeamManagementRouteImport } from './routes/_authenticated/team-management'
import { Route as AuthenticatedSilosRouteImport } from './routes/_authenticated/silos'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSensorsRouteImport } from './routes/_authenticated/sensors'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNotAllowedRouteImport } from './routes/_authenticated/not-allowed'
import { Route as AuthenticatedInsuranceRouteImport } from './routes/_authenticated/insurance'
import { Route as AuthenticatedGrainBatchesRouteImport } from './routes/_authenticated/grain-batches'
import { Route as AuthenticatedGrainAlertsRouteImport } from './routes/_authenticated/grain-alerts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBuyersRouteImport } from './routes/_authenticated/buyers'
import { Route as AuthenticatedActuatorsRouteImport } from './routes/_authenticated/actuators'
import { Route as AuthenticatedActivityLogsRouteImport } from './routes/_authenticated/activity-logs'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform.index'
import { Route as AuthenticatedPlatformUsersRouteImport } from './routes/_authenticated/platform.users'
import { Route as AuthenticatedPlatformTenantsRouteImport } from './routes/_authenticated/platform.tenants'
import { Route as ApiPublicHooksSensorOfflineDetectorRouteImport } from './routes/api/public/hooks/sensor-offline-detector'
import { Route as ApiPublicHooksAlertsEscalationRouteImport } from './routes/api/public/hooks/alerts-escalation'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTraceabilityRoute =
  AuthenticatedTraceabilityRouteImport.update({
    id: '/traceability',
    path: '/traceability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamManagementRoute =
  AuthenticatedTeamManagementRouteImport.update({
    id: '/team-management',
    path: '/team-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSilosRoute = AuthenticatedSilosRouteImport.update({
  id: '/silos',
  path: '/silos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSensorsRoute = AuthenticatedSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotAllowedRoute = AuthenticatedNotAllowedRouteImport.update({
  id: '/not-allowed',
  path: '/not-allowed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsuranceRoute = AuthenticatedInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrainBatchesRoute =
  AuthenticatedGrainBatchesRouteImport.update({
    id: '/grain-batches',
    path: '/grain-batches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGrainAlertsRoute =
  AuthenticatedGrainAlertsRouteImport.update({
    id: '/grain-alerts',
    path: '/grain-alerts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyersRoute = AuthenticatedBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActuatorsRoute = AuthenticatedActuatorsRouteImport.update({
  id: '/actuators',
  path: '/actuators',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityLogsRoute =
  AuthenticatedActivityLogsRouteImport.update({
    id: '/activity-logs',
    path: '/activity-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformUsersRoute =
  AuthenticatedPlatformUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformTenantsRoute =
  AuthenticatedPlatformTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const ApiPublicHooksSensorOfflineDetectorRoute =
  ApiPublicHooksSensorOfflineDetectorRouteImport.update({
    id: '/api/public/hooks/sensor-offline-detector',
    path: '/api/public/hooks/sensor-offline-detector',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAlertsEscalationRoute =
  ApiPublicHooksAlertsEscalationRouteImport.update({
    id: '/api/public/hooks/alerts-escalation',
    path: '/api/public/hooks/alerts-escalation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/actuators': typeof AuthenticatedActuatorsRoute
  '/buyers': typeof AuthenticatedBuyersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grain-alerts': typeof AuthenticatedGrainAlertsRoute
  '/grain-batches': typeof AuthenticatedGrainBatchesRoute
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/not-allowed': typeof AuthenticatedNotAllowedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/sensors': typeof AuthenticatedSensorsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/silos': typeof AuthenticatedSilosRoute
  '/team-management': typeof AuthenticatedTeamManagementRoute
  '/traceability': typeof AuthenticatedTraceabilityRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/platform/tenants': typeof AuthenticatedPlatformTenantsRoute
  '/platform/users': typeof AuthenticatedPlatformUsersRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
  '/api/public/hooks/alerts-escalation': typeof ApiPublicHooksAlertsEscalationRoute
  '/api/public/hooks/sensor-offline-detector': typeof ApiPublicHooksSensorOfflineDetectorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/actuators': typeof AuthenticatedActuatorsRoute
  '/buyers': typeof AuthenticatedBuyersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grain-alerts': typeof AuthenticatedGrainAlertsRoute
  '/grain-batches': typeof AuthenticatedGrainBatchesRoute
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/not-allowed': typeof AuthenticatedNotAllowedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/sensors': typeof AuthenticatedSensorsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/silos': typeof AuthenticatedSilosRoute
  '/team-management': typeof AuthenticatedTeamManagementRoute
  '/traceability': typeof AuthenticatedTraceabilityRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/platform/tenants': typeof AuthenticatedPlatformTenantsRoute
  '/platform/users': typeof AuthenticatedPlatformUsersRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
  '/api/public/hooks/alerts-escalation': typeof ApiPublicHooksAlertsEscalationRoute
  '/api/public/hooks/sensor-offline-detector': typeof ApiPublicHooksSensorOfflineDetectorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/_authenticated/actuators': typeof AuthenticatedActuatorsRoute
  '/_authenticated/buyers': typeof AuthenticatedBuyersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/grain-alerts': typeof AuthenticatedGrainAlertsRoute
  '/_authenticated/grain-batches': typeof AuthenticatedGrainBatchesRoute
  '/_authenticated/insurance': typeof AuthenticatedInsuranceRoute
  '/_authenticated/not-allowed': typeof AuthenticatedNotAllowedRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/_authenticated/sensors': typeof AuthenticatedSensorsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/silos': typeof AuthenticatedSilosRoute
  '/_authenticated/team-management': typeof AuthenticatedTeamManagementRoute
  '/_authenticated/traceability': typeof AuthenticatedTraceabilityRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/platform/tenants': typeof AuthenticatedPlatformTenantsRoute
  '/_authenticated/platform/users': typeof AuthenticatedPlatformUsersRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
  '/api/public/hooks/alerts-escalation': typeof ApiPublicHooksAlertsEscalationRoute
  '/api/public/hooks/sensor-offline-detector': typeof ApiPublicHooksSensorOfflineDetectorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/activity-logs'
    | '/actuators'
    | '/buyers'
    | '/dashboard'
    | '/grain-alerts'
    | '/grain-batches'
    | '/insurance'
    | '/not-allowed'
    | '/notifications'
    | '/platform'
    | '/sensors'
    | '/settings'
    | '/silos'
    | '/team-management'
    | '/traceability'
    | '/warehouses'
    | '/auth/reset-password'
    | '/platform/tenants'
    | '/platform/users'
    | '/platform/'
    | '/api/public/hooks/alerts-escalation'
    | '/api/public/hooks/sensor-offline-detector'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/activity-logs'
    | '/actuators'
    | '/buyers'
    | '/dashboard'
    | '/grain-alerts'
    | '/grain-batches'
    | '/insurance'
    | '/not-allowed'
    | '/notifications'
    | '/sensors'
    | '/settings'
    | '/silos'
    | '/team-management'
    | '/traceability'
    | '/warehouses'
    | '/auth/reset-password'
    | '/platform/tenants'
    | '/platform/users'
    | '/platform'
    | '/api/public/hooks/alerts-escalation'
    | '/api/public/hooks/sensor-offline-detector'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/activity-logs'
    | '/_authenticated/actuators'
    | '/_authenticated/buyers'
    | '/_authenticated/dashboard'
    | '/_authenticated/grain-alerts'
    | '/_authenticated/grain-batches'
    | '/_authenticated/insurance'
    | '/_authenticated/not-allowed'
    | '/_authenticated/notifications'
    | '/_authenticated/platform'
    | '/_authenticated/sensors'
    | '/_authenticated/settings'
    | '/_authenticated/silos'
    | '/_authenticated/team-management'
    | '/_authenticated/traceability'
    | '/_authenticated/warehouses'
    | '/auth/reset-password'
    | '/_authenticated/platform/tenants'
    | '/_authenticated/platform/users'
    | '/_authenticated/platform/'
    | '/api/public/hooks/alerts-escalation'
    | '/api/public/hooks/sensor-offline-detector'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksAlertsEscalationRoute: typeof ApiPublicHooksAlertsEscalationRoute
  ApiPublicHooksSensorOfflineDetectorRoute: typeof ApiPublicHooksSensorOfflineDetectorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/traceability': {
      id: '/_authenticated/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof AuthenticatedTraceabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-management': {
      id: '/_authenticated/team-management'
      path: '/team-management'
      fullPath: '/team-management'
      preLoaderRoute: typeof AuthenticatedTeamManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/silos': {
      id: '/_authenticated/silos'
      path: '/silos'
      fullPath: '/silos'
      preLoaderRoute: typeof AuthenticatedSilosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sensors': {
      id: '/_authenticated/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof AuthenticatedSensorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/not-allowed': {
      id: '/_authenticated/not-allowed'
      path: '/not-allowed'
      fullPath: '/not-allowed'
      preLoaderRoute: typeof AuthenticatedNotAllowedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurance': {
      id: '/_authenticated/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof AuthenticatedInsuranceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grain-batches': {
      id: '/_authenticated/grain-batches'
      path: '/grain-batches'
      fullPath: '/grain-batches'
      preLoaderRoute: typeof AuthenticatedGrainBatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grain-alerts': {
      id: '/_authenticated/grain-alerts'
      path: '/grain-alerts'
      fullPath: '/grain-alerts'
      preLoaderRoute: typeof AuthenticatedGrainAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyers': {
      id: '/_authenticated/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof AuthenticatedBuyersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actuators': {
      id: '/_authenticated/actuators'
      path: '/actuators'
      fullPath: '/actuators'
      preLoaderRoute: typeof AuthenticatedActuatorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity-logs': {
      id: '/_authenticated/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof AuthenticatedActivityLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/users': {
      id: '/_authenticated/platform/users'
      path: '/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof AuthenticatedPlatformUsersRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/tenants': {
      id: '/_authenticated/platform/tenants'
      path: '/tenants'
      fullPath: '/platform/tenants'
      preLoaderRoute: typeof AuthenticatedPlatformTenantsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/api/public/hooks/sensor-offline-detector': {
      id: '/api/public/hooks/sensor-offline-detector'
      path: '/api/public/hooks/sensor-offline-detector'
      fullPath: '/api/public/hooks/sensor-offline-detector'
      preLoaderRoute: typeof ApiPublicHooksSensorOfflineDetectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/alerts-escalation': {
      id: '/api/public/hooks/alerts-escalation'
      path: '/api/public/hooks/alerts-escalation'
      fullPath: '/api/public/hooks/alerts-escalation'
      preLoaderRoute: typeof ApiPublicHooksAlertsEscalationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPlatformRouteChildren {
  AuthenticatedPlatformTenantsRoute: typeof AuthenticatedPlatformTenantsRoute
  AuthenticatedPlatformUsersRoute: typeof AuthenticatedPlatformUsersRoute
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
}

const AuthenticatedPlatformRouteChildren: AuthenticatedPlatformRouteChildren = {
  AuthenticatedPlatformTenantsRoute: AuthenticatedPlatformTenantsRoute,
  AuthenticatedPlatformUsersRoute: AuthenticatedPlatformUsersRoute,
  AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
}

const AuthenticatedPlatformRouteWithChildren =
  AuthenticatedPlatformRoute._addFileChildren(
    AuthenticatedPlatformRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityLogsRoute: typeof AuthenticatedActivityLogsRoute
  AuthenticatedActuatorsRoute: typeof AuthenticatedActuatorsRoute
  AuthenticatedBuyersRoute: typeof AuthenticatedBuyersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGrainAlertsRoute: typeof AuthenticatedGrainAlertsRoute
  AuthenticatedGrainBatchesRoute: typeof AuthenticatedGrainBatchesRoute
  AuthenticatedInsuranceRoute: typeof AuthenticatedInsuranceRoute
  AuthenticatedNotAllowedRoute: typeof AuthenticatedNotAllowedRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRouteWithChildren
  AuthenticatedSensorsRoute: typeof AuthenticatedSensorsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSilosRoute: typeof AuthenticatedSilosRoute
  AuthenticatedTeamManagementRoute: typeof AuthenticatedTeamManagementRoute
  AuthenticatedTraceabilityRoute: typeof AuthenticatedTraceabilityRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityLogsRoute: AuthenticatedActivityLogsRoute,
  AuthenticatedActuatorsRoute: AuthenticatedActuatorsRoute,
  AuthenticatedBuyersRoute: AuthenticatedBuyersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGrainAlertsRoute: AuthenticatedGrainAlertsRoute,
  AuthenticatedGrainBatchesRoute: AuthenticatedGrainBatchesRoute,
  AuthenticatedInsuranceRoute: AuthenticatedInsuranceRoute,
  AuthenticatedNotAllowedRoute: AuthenticatedNotAllowedRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRouteWithChildren,
  AuthenticatedSensorsRoute: AuthenticatedSensorsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSilosRoute: AuthenticatedSilosRoute,
  AuthenticatedTeamManagementRoute: AuthenticatedTeamManagementRoute,
  AuthenticatedTraceabilityRoute: AuthenticatedTraceabilityRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksAlertsEscalationRoute: ApiPublicHooksAlertsEscalationRoute,
  ApiPublicHooksSensorOfflineDetectorRoute:
    ApiPublicHooksSensorOfflineDetectorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
